name: code_checker
description: Static source code analytics tool that helps analyse and improve quality.
version: 0.0.7
homepage: https://github.com/dart-code-checker-project/code-checker

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  analyzer: '>=0.39.3 <0.42.0'
  meta: ^1.1.6
  source_span: ^1.4.1

dev_dependencies:
  coverage: ^0.14.0
  dependency_validator: ^2.0.1
  http_multi_server: ^2.2.0       # for valid resolve dependencies
  lcov: '>=5.7.0 <7.0.0'
  mockito: ^4.1.1
  path: ^1.7.0
  pedantic: ^1.9.2
  test: ^1.15.7

dependency_validator:
  ignore:
    - http_multi_server
