name: code_checker
version: 0.7.0
description: Static source code analytics tool that helps analyse and improve quality.
homepage: https://dart-code-checker-project.github.io/code-checker
repository: https://github.com/dart-code-checker-project/code-checker
issue_tracker: https://github.com/dart-code-checker-project/code-checker/issues

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  analyzer: ^0.41.2
  analyzer_plugin: ^0.4.0
  args: ^1.6.0
  glob: ^1.2.0
  meta: ^1.3.0
  path: ^1.8.0
  source_span: ^1.8.1
  yaml: ^2.2.1

dev_dependencies:
  coverage: ^0.15.2
  html: ^0.14.0
  lcov: ^6.0.0
  markdown: ^3.0.0
  mockito: ^4.1.4
  pedantic: ^1.10.0
  test: ^1.16.2

executables:
  checker:
