name: code_checker
description: Code analytics tool that helps analyse and improve quality.
version: 0.0.0
homepage: https://github.com/dart-code-checker-project/code-checker

environment:
  sdk: ">=2.8.0 <3.0.0"

dev_dependencies:
  dependency_validator: ^2.0.0
  pedantic: ^1.9.2
