name: code_checker
version: 0.4.1
description: Static source code analytics tool that helps analyse and improve quality.
homepage: https://dart-code-checker-project.github.io/code-checker
repository: https://github.com/dart-code-checker-project/code-checker
issue_tracker: https://github.com/dart-code-checker-project/code-checker/issues

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  analyzer: '>=0.39.3 <0.42.0'
  analyzer_plugin: '>=0.2.1 <0.5.0'
  args: ^1.4.4
  meta: ^1.1.6
  path: ^1.7.0
  source_span: ^1.4.1
  yaml: ^2.2.0

dev_dependencies:
  coverage: '>=0.14.2 <0.16.0'
  http_multi_server: ^2.2.0       # for valid resolve dependencies
  lcov: '>=5.7.0 <7.0.0'
  mockito: ^4.1.1
  pedantic: ^1.9.2
  test: ^1.15.7

executables:
  checker:

dependency_validator:
  ignore:
    - http_multi_server
